### PR TITLE
add class properties so that query parameters can be populated using …

### PR DESCRIPTION
**Pull request by AdrianBathurst**
…instance properties + fix for issue #45

### CODE REVIEW

**Comment by AdrianBathurst** [comment]
This will add table/query specific properties to the class that would allow for setting fields in a type-safe way for insert and update statements.

**Comment by bbsimonbb** [comment]
I quite like the idea. Some queries may have dozens or more parameters so clearly, passing them as method arguments gets unwieldy. There's a couple of problems though. You've duplicated the code generation routines, and doubled the number of substantive methods to maintain, so I can't accept this as is. 

One option would be to put the properties on the class as you suggest and delete the parameters from the real execute methods. Then, if a query has say 5 or less params, just provide an overload with parameters that sets the public properties and calls the parameterless version. This way, there would be no duplicated code, and the methods would present as overloads, which is nice. The generated interfaces would need to be updated as well.

The other option would be to create a parameters poco. A separate class. I don't know if this would have any advantages?

Thanks for your interest in the project !

**Comment by AdrianBathurst** [comment]
I know there's the duplication of methods, but I thought I'd keep the modification as minimalist as possible and remain backward compatible. My original modification did away with the parameter methods altogether, but then reverted because of above thoughts.

Please adjust as you wish. Ultimately I/we want to work with an object's properties, and not have to fill parameters. Properties in the same class or a separate class...you can decide what's best. Currently it's working fine in the same class, but if you have other ideas, please go ahead.

Could you include the other modifications though, they cured some little niggles...

1 - VS kept prompting to fix line endings, my modifications stopped that.
2 - when generating insert/update queries, I kept on having to do 3 saves....1st to auto generate the parameters, 2nd after your code modified the double dash thing, then a 3rd save is required to finish off. My mods to ScaffoldInsert.sql & ScaffoldUpdate.sql scripts stopped that. Now the correct two saves are required...1st to auto generate parameters, 2nd to finish off code gen.
3 - mod to BackwardCompatibility.cs to fix issue #45 

...and thank you for this project!

**Comment by AdrianBathurst** [comment]
> if a query has say 5 or less params, just provide an overload with parameters...

I think this will lead to confusion. If there are more than 5, then use instance properties....will raise some "_but why_"'s.

I think parameter-less methods is probably the way forward. With your animated example, using instance properties, this is super simple and intuitive without parameters...
`foreach (var cust in new GetCustomers() { MySearchTerm = "fran" }.Execute())`

**Comment by AdrianBathurst** [comment]
Made an update that removes the use of query parameters.

**Pull request closed without merging**
