### PR TITLE
Output params, Table Valued Functions, In-memory compilation, Inserts…

### PR DESCRIPTION
**Pull request by bbsimonbb**
… and Updates, Params via Object Initialisation,

### CODE REVIEW

**Comment by AdrianBathurst** [comment]
Awesome, looking forward to see what's added/changed. Thanks!

**Comment by bbsimonbb** [comment]
Hey Adrian how are you? This PR implements your idea of supplying params via object initialisation, so I'd welcome feedback on that. I've refactored the whole thing to try and facilitate testing and reuse. Would you like to look through and comment on the PR before I merge ?

**Comment by AdrianBathurst** [comment]
Hi, all good thanks! Sorry for delay. Despite the world lock-downs, I'm still working. I'll try have a look tomorrow. :)

**Comment by AdrianBathurst** [comment]
I'm trying to test this update. For some queries that I run, it generates the error below. It seems to happen to insert & update queries. The `If you're using...` message also repeats for all queries.

I'm testing this via running your project with 'Start' debug, which launches what's supposed to be a clean debug instance of Visual Studio. In that instance, I run a test project that has a number of test queries.

```
If you're using and enjoying QueryFirst, please leave a review!
https://marketplace.visualstudio.com/items?itemName=bbsimonbb.QueryFirst#review-details
Sequence contains no elements   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at QueryFirst.Providers.SqlClient.GetParamInfoSecondAttempt(String paramName, String connectionString) in J:\query-first-simons\QueryFirst\Providers\SqlClient.cs:line 137
   at QueryFirst.Providers.SqlClient.ParseDeclaredParameters(String queryText, String connectionString) in J:\query-first-simons\QueryFirst\Providers\SqlClient.cs:line 34
   at QueryFirst._8ParseOrFindDeclaredParams.Go(State& state) in J:\query-first-simons\QueryFirst\StateAndTransitions\_8ParseOrFindDeclaredParams.cs:line 18
   at QueryFirst.Conductor.ProcessOneQuery(Document queryDoc) in J:\query-first-simons\QueryFirst\Conductor.cs:line 142If you're using and enjoying QueryFirst, please leave a review!
https://marketplace.visualstudio.com/items?itemName=bbsimonbb.QueryFirst#review-details
Already registered
QueryFirst generated wrapper class for sp.sql
If you're using and enjoying QueryFirst, please leave a review!
https://marketplace.visualstudio.com/items?itemName=bbsimonbb.QueryFirst#review-details
Already registered
Sequence contains no elements   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at QueryFirst.Providers.SqlClient.GetParamInfoSecondAttempt(String paramName, String connectionString) in J:\query-first-simons\QueryFirst\Providers\SqlClient.cs:line 137
   at QueryFirst.Providers.SqlClient.ParseDeclaredParameters(String queryText, String connectionString) in J:\query-first-simons\QueryFirst\Providers\SqlClient.cs:line 34
   at QueryFirst._8ParseOrFindDeclaredParams.Go(State& state) in J:\query-first-simons\QueryFirst\StateAndTransitions\_8ParseOrFindDeclaredParams.cs:line 18
   at QueryFirst.Conductor.ProcessOneQuery(Document queryDoc) in J:\query-first-simons\QueryFirst\Conductor.cs:line 142
```

**Comment by bbsimonbb** [comment]
Hey thanks for looking at this. I've committed a couple of changes to spam less, and to report the type if we have trouble matching it. Would you like to share your test project. I really need better testing around the new stuff: user defined types and table valued params.

**Comment by AdrianBathurst** [comment]
It is 'spamming' less now, however, the "Already Registered" message still repeats after each save.

There were some missing database type conversions missing that made it break. In  `Providers/SqlClient/SqlDbType2DbType.cs`, here is the full list you can add...

```
static TypeConvertor()
{
    _DbTypeList.Add(new DbTypeMapEntry(typeof(Int64), DbType.Int64, SqlDbType.BigInt));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(byte[]), DbType.Binary, SqlDbType.Binary));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(bool), DbType.Boolean, SqlDbType.Bit));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(string), DbType.AnsiStringFixedLength, SqlDbType.Char));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(DateTime), DbType.Date, SqlDbType.Date));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(DateTime), DbType.DateTime, SqlDbType.DateTime));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(DateTime), DbType.DateTime2, SqlDbType.DateTime2));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(Decimal), DbType.Decimal, SqlDbType.Decimal));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(double), DbType.Double, SqlDbType.Float));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(byte[]), DbType.Binary, SqlDbType.Image));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(Int32), DbType.Int32, SqlDbType.Int));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(Decimal), DbType.Decimal, SqlDbType.Money));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(string), DbType.StringFixedLength, SqlDbType.NChar));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(string), DbType.String, SqlDbType.NText));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(string), DbType.String, SqlDbType.NVarChar));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(Single), DbType.Single, SqlDbType.Real));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(DateTime), DbType.DateTime, SqlDbType.SmallDateTime));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(Int16), DbType.Int16, SqlDbType.SmallInt));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(decimal), DbType.Decimal, SqlDbType.SmallMoney));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(string), DbType.String, SqlDbType.Text));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(DateTime), DbType.Time, SqlDbType.Time));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(byte[]), DbType.Binary, SqlDbType.Timestamp));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(byte), DbType.Byte, SqlDbType.TinyInt));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(Guid), DbType.Guid, SqlDbType.UniqueIdentifier));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(byte[]), DbType.Binary, SqlDbType.VarBinary));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(object), DbType.Object, SqlDbType.Variant));
    _DbTypeList.Add(new DbTypeMapEntry(typeof(string), DbType.AnsiString, SqlDbType.VarChar));
}
```

In `StateAndTransitions/_5ScaffoldUpdateOrInsert.cs` line 29, can you add `timestamp` to the list so it's excluded as that breaks inserts/updates if there's a timestamp column...
```
).Where(col => (!col.IsIdentity && !(new string[] { "text","ntext","image","timestamp" }).Contains(col.TypeDb) /* && !col.IsComputed*/));
```
Timestamp columns are not required for insert/update as the database auto updates these.

In `Providers/SqlClient.cs` after line 102, can you add this...
```
if (typeOnly.ToLower() == "sql_variant")
    typeOnly = "Variant";
```

Same file, line 211, add the error message to get some clues as to what's wrong...
```
outputMessage = $"Unable to find undeclared parameters. ({ex.Message}) Make sure your parameters are declared in the designTime section\n";
```

**Comment by AdrianBathurst** [comment]
Here is the test project...
[QF_Test.zip](https://github.com/bbsimonbb/query-first/files/4443574/QF_Test.zip)

**Comment by bbsimonbb** [comment]
Can you please share a backup of the cms database that the QF_Test needs ! Thanks.

**Comment by AdrianBathurst** [comment]
The database is in the "db" folder, you just need to attach it.
________________________________

**Comment by bbsimonbb** [comment]
Hi. I figured out the db thing straight after asking. Doh. 

Adrian this is super work thanks. The test project is really thorough. I've been dreaming of something like this. I've got it working locally for everything but sql_variant, which will take a bit of thought. I'll be back to you...

**Comment by AdrianBathurst** [comment]
Could you also add support for `FOR JSON` query results. This query type auto generates a column called `JSON_F52E2B61-18A1-11d1-B105-00805F49916B` which breaks c#.

Replace line 84 and 85 in `SchemaFetching/AdoSchemaFetcher.cs` with below to rename the column:

```
if (!string.IsNullOrEmpty(SchemaTable.Rows[i].Field<string>(j)))
{
    var colName = SchemaTable.Rows[i].Field<string>(j);
    qf.ColumnName = colName.StartsWith("JSON_") ? "Json" : colName; // rename column for 'FOR JSON' queries
}
```

Sample query for test project `Json.sql`:
```
select BigInt, Bit, DateTime, NVarChar from AllTypes for json auto;
```

Sample code for test project:
```
var jsonResult = new System.Text.StringBuilder();
var result = new DAL.Json().Execute();
if (result.Count == 0)
    jsonResult.Append("[]");
else
{
    foreach (var x in result)
    {
        jsonResult.Append(x.Json);
    }
}

var json = jsonResult.ToString();
```

**Comment by AdrianBathurst** [comment]
Thanks again for the update! Could you bump the version and publish to the marketplace?

**Comment by bbsimonbb** [comment]
I'm locked out of my microsoft account. It was keyed on an old work email and I've moved to Australia from France. Even knowing the password is not saving me. I'll update the marketplace as soon as I get it sorted.

**Pull request merged**
