### PR TITLE
connects editor window to DB

### PR DESCRIPTION
**Pull request by bbsimonbb**
I bled to implement this. This change, if everything works, means that a newly opened editor window will connect to the DB using the QF default connection.

### CODE REVIEW

**Comment by AdrianBathurst** [comment]
Nice!

**Comment by AdrianBathurst** [comment]
Works fine when I test it in the development environment... Open QueryFirst project, then click Start to load and use the QF_Test project, open a query, it auto connects to the db.

However, I have installed the latest version from Marketplace (v1.1.3) and that is not working. I'm opening the same QF_Test project. Open a query, it does not auto connect to the db. It's behaving just as it was before this update. Even creating a new query to "Trust" the extension doesn't kick it into action.

**Comment by bbsimonbb** [comment]
Yep. I'm working through an issue with VS2017. I'm guessing you're on VS2019? On VS2017 I've seen it hang the environment, so I pulled the feature until I've resolved the issue.

**Comment by AdrianBathurst** [comment]
Yes, I'm using VS2019.

The very first time I opened the QF_Test project in the development environment, it did hang also. I had two instances of QF_Test open, so I assumed it may have been that. I closed both and restarted, then it was fine. I tried a few times and it didn't hang again. Might be related?

**Pull request merged**
