### PR TITLE
VS2022 support

### PR DESCRIPTION
**Pull request by AdrianBathurst**
Added VS2022 support with backward compatibility.
Created two separate projects for vs16 and vs17 both linked to a shared project.
Updated projects to .net framework 4.8
Converted projects to use PackageReference
Only tested against SqlClient

### CODE REVIEW

**Comment by bbsimonbb** [comment]
Adrian I'm a bit stuck here. I can't get your PR to build on my machine. I'm following my nose to try to correct the dependency errors. I updated Microsoft.VSSDK.BuildTools from 15.8 to 17.1.  and Microsoft.VisualStudio.Shell.Immutable.10.0 from version 10.0.0 to 15.0.0. Each update seemed to move me forward, but now I've got conflict on ServiceProgressData. These types of issues kill my will to live. The other issue is that we're in query-first, not QueryFirstX, so I will need to port this work to the new repo. We didn't talk enough before getting into it. A workaround would be for you to provide me with a VSIX that I can put on the marketplace site ?

**Comment by AdrianBathurst** [comment]
Here are the Visx's

[Visx.zip](https://github.com/bbsimonbb/query-first/files/7748210/Visx.zip)

Yeap, these updates can be a pain. Did nuget restore? I was hoping that nuget restore would make it "just work" for you.

**Comment by AdrianBathurst** [comment]
Maybe delete the `obj` and `bin/Debug` & `Release` folders. There was a stage when I was getting errors. After deleting these, they went away.

I did not update any of the vs16 nuget packages as that broke it, so I kept that project with existing versions.

**Comment by AdrianBathurst** [comment]
@bbsimonbb On another pc that had my original QF project on it that was pre vs2022 conversion I managed to get it to build ok without modification.

Steps:

1. Opened VS2019, uninstalled the current QF Extension, then closed it
2. Deleted the QF project folder/files from pc
3. Re-cloned the QF git repo to the same location it was deleted from
4. Installed VS2022, _when installing, also select this..._

.
image


.
5. Opened the QF project in VS2022 (_on open, it automatically downloaded the missing nuget items_)
6. Right-clicked the `QueryFirst` project and selected `Set as Startup Project`
7. Press `Start`, it launched a test instance of VS2022, loaded the test project...tested all works ok
8. Right-clicked the `QueryFirst_VS16` project and selected `Set as Startup Project`
9. Selected to run VS2019...

image



10. It launched a test instance of VS2019, loaded the test project...tested all works ok

Gut feel says it's the deleting of files and re-cloning that does the trick as it gets rid of any redundant files lying around.

**Pull request merged**
